import { useState } from "react";
import { json, redirect, type LoaderFunctionArgs, type ActionFunctionArgs } from "@remix-run/node";
import { useLoaderData, useFetcher } from "@remix-run/react";
import {
  Page,
  Layout,
  Card,
  Text,
  Button,
  Checkbox,
  BlockStack,
  Box,
  Divider,
  Banner
} from "@shopify/polaris";
import { authenticate } from "../shopify.server";
import db from "../db.server";

export const loader = async ({ request }: LoaderFunctionArgs) => {
  const { session } = await authenticate.admin(request);
  const shop = await db.shop.findUnique({ where: { shop: session.shop } });

  // If already accepted, no need to be here, send them to dashboard
  if (shop?.termsAccepted) {
    const url = new URL(request.url);
    url.pathname = "/app";
    return redirect(url.toString());
  }

  return json({ shop: session.shop });
};

export const action = async ({ request }: ActionFunctionArgs) => {
  const { session } = await authenticate.admin(request);
  const formData = await request.formData();
  
  const accepted = formData.get("accepted") === "true";

  if (!accepted) {
    return json({ status: "error", message: "You must agree to the terms." });
  }

  // Update DB
  await db.shop.update({
    where: { shop: session.shop },
    data: {
      termsAccepted: true,
      termsAcceptedAt: new Date(),
    }
  });

  return redirect("/app");
};

export default function TermsOfService() {
  const fetcher = useFetcher();
  const [checked, setChecked] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const handleAccept = () => {
    setIsSubmitting(true);
    fetcher.submit({ accepted: "true" }, { method: "POST" });
  };

  return (
    <Page title="Terms of Service" narrowWidth>
      <Layout>
        <Layout.Section>
          <Card>
            <BlockStack gap="500">
              <Banner tone="warning" title="Action Required">
                <p>Please accept the Terms of Service to continue using Net Terms Tracker.</p>
              </Banner>

              <Box paddingBlock="200" paddingInline="0">
                <BlockStack gap="400">
                    {/* LEGAL TEXT CONTENT */}
                    <Text variant="headingLg" as="h1">Terms of Service</Text>
                    <Text variant="bodySm" as="p" tone="subdued">Last Updated: {new Date().toLocaleDateString()}</Text>
                    
                    <Divider />
                    
                    <Text variant="headingMd" as="h2">1. Nature of the Service (The "Utility" Clause)</Text>
                    <Text as="p">
                        "Net Terms Tracker" (the "Service") is strictly a data management and invoicing utility.
                    </Text>
                    <ul style={{ paddingLeft: '20px', margin: '0' }}>
                        <li><strong>Not a Financial Institution:</strong> The Service is <strong>not</strong> a bank, lender, or payment processor. We do not underwrite debt, guarantee payment, or insure against default.</li>
                        <li><strong>Merchant Responsibility:</strong> You (the "Merchant") are solely responsible for assessing the creditworthiness of your customers. The decision to extend "Net Terms" or credit to any buyer is made at your sole discretion and risk.</li>
                    </ul>

                    <Text variant="headingMd" as="h2">2. Limitation of Liability</Text>
                    <Text as="p">To the maximum extent permitted by law, we shall not be liable for:</Text>
                    <ul style={{ paddingLeft: '20px', margin: '0' }}>
                        <li><strong>Non-Payment:</strong> Any failure of your customers to pay invoices generated by the Service.</li>
                        <li><strong>Data Errors:</strong> Any financial loss resulting from incorrect due dates, tax calculations, or invoice totals. You agree to verify all financial data before acting on it.</li>
                        <li><strong>Service Interruptions:</strong> Any inability to access invoice data during downtime or maintenance.</li>
                    </ul>

                    <Text variant="headingMd" as="h2">3. Data Accuracy & Taxes</Text>
                    <Text as="p">
                        The Service calculates due dates based on the logic you define (e.g., "Net 30"). You acknowledge that the Service does not automatically remit taxes or comply with local invoicing regulations (e.g., VAT, GST) on your behalf. You remain the "Merchant of Record" for all transactions.
                    </Text>

                    <Text variant="headingMd" as="h2">4. Termination</Text>
                    <Text as="p">We reserve the right to terminate access to the Service immediately if we detect:</Text>
                    <ul style={{ paddingLeft: '20px', margin: '0' }}>
                        <li>Use of the Service for money laundering or illegal financing.</li>
                        <li>Violation of Shopify's Acceptable Use Policy (AUP).</li>
                    </ul>
                </BlockStack>
              </Box>

              <Divider />

              {/* AGREEMENT FORM */}
              <Box paddingBlockStart="200">
                  <BlockStack gap="400">
                    <Checkbox
                        label="I have read and agree to the Terms of Service."
                        checked={checked}
                        onChange={(newChecked) => setChecked(newChecked)}
                    />
                    
                    <Button 
                        variant="primary" 
                        disabled={!checked} 
                        loading={isSubmitting}
                        onClick={handleAccept}
                        fullWidth
                    >
                        Agree & Continue
                    </Button>
                  </BlockStack>
              </Box>

            </BlockStack>
          </Card>
        </Layout.Section>
      </Layout>
    </Page>
  );
}